"""
pi_plots.py

Plot the distribution of Monte Carlo estimates of pi and the corresponding
errors, using data generated by the pi_statistics module.
"""

from __future__ import annotations

import argparse
import math
from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np


def parse_arguments() -> argparse.Namespace:
    """Parse command-line arguments for the pi plotting script.

    Returns:
        argparse.Namespace: Parsed arguments including the input file path,
        number of histogram bins, and the output directory.
    """
    parser = argparse.ArgumentParser(
        description=(
            "Plot the distribution of Monte Carlo estimates of pi and their "
            "errors relative to the true value."
        )
    )
    parser.add_argument(
        "--input_path",
        type=str,
        default="results/raw/pi_estimates.npy",
        help=(
            "Path to the NumPy file containing the array of pi estimates "
            "(default: results/raw/pi_estimates.npy)."
        ),
    )
    parser.add_argument(
        "--number_of_bins",
        type=int,
        default=20,
        help="Number of bins to use in the histograms (default: 20).",
    )
    parser.add_argument(
        "--output_directory",
        type=str,
        default="results/figures",
        help=(
            "Directory where histogram plots will be saved as PNG files "
            "(default: results/figures)."
        ),
    )
    return parser.parse_args()


def load_pi_estimates(input_path: str) -> np.ndarray:
    """Load an array of pi estimates from a NumPy file.

    Args:
        input_path (str): Path to a .npy file produced by pi_statistics.

    Returns:
        np.ndarray: One-dimensional array of pi estimates.
    """
    estimates = np.load(input_path)
    if estimates.ndim != 1:
        raise ValueError("Expected a one-dimensional array of pi estimates.")
    return estimates


def make_pi_plots(
    estimates: np.ndarray,
    number_of_bins: int,
    output_directory: str,
) -> None:
    """Create and save histograms of pi estimates and their errors.

    Args:
        estimates (np.ndarray): Array of Monte Carlo estimates of pi.
        number_of_bins (int): Number of bins for the histograms.
        output_directory (str): Directory where PNG files will be saved.
    """
    output_dir_path = Path(output_directory)
    output_dir_path.mkdir(parents=True, exist_ok=True)

    true_pi = math.pi
    mean_estimate = float(np.mean(estimates))
    standard_deviation = float(np.std(estimates, ddof=1))
    errors = estimates - true_pi

    # Histogram of pi estimates
    plt.figure()
    plt.hist(estimates, bins=number_of_bins, density=True, alpha=0.75)
    plt.axvline(true_pi, color="k", linestyle="--", label="True pi")
    plt.xlabel("Estimated pi")
    plt.ylabel("Probability density")
    plt.title("Distribution of Monte Carlo estimates of pi")
    plt.legend()
    estimates_path = (
        output_dir_path / "pi_estimates_histogram.png"
    )
    plt.savefig(estimates_path, dpi=300, bbox_inches="tight")
    plt.close()

    # Histogram of errors
    plt.figure()
    plt.hist(errors, bins=number_of_bins, density=True, alpha=0.75)
    plt.axvline(0.0, color="k", linestyle="--", label="Zero error")
    plt.xlabel("Estimate minus true pi")
    plt.ylabel("Probability density")
    plt.title("Distribution of errors in pi estimates")
    plt.legend()
    errors_path = (
        output_dir_path / "pi_error_histogram.png"
    )
    plt.savefig(errors_path, dpi=300, bbox_inches="tight")
    plt.close()

    print(f"Number of estimates          : {len(estimates)}")
    print(f"Sample mean of estimates     : {mean_estimate:.6f}")
    print(f"Sample standard deviation    : {standard_deviation:.6e}")
    print(f"Mean absolute error          : {np.mean(np.abs(errors)):.6e}")
    print(f"Saved plots to {output_dir_path}")







def main() -> None:
    """Entry point for generating plots of pi estimator statistics."""
    arguments = parse_arguments()
    estimates = load_pi_estimates(input_path=arguments.input_path)
    make_pi_plots(
        estimates=estimates,
        number_of_bins=arguments.number_of_bins,
        output_directory=arguments.output_directory,
    )


if __name__ == "__main__":
    main()
